# Generated by Django 4.1.2 on 2022-10-31 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category name')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Company name')),
                ('details', models.TextField(verbose_name='Details')),
                ('email', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('logo', models.FileField(upload_to='', verbose_name='Logo')),
                ('address_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address Line 1')),
                ('address_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('rating', models.SmallIntegerField(default=0, verbose_name='Raating')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.category', verbose_name='Category')),
                ('managed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Managed By')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('desc', models.TextField(verbose_name='Description')),
                ('banner', models.ImageField(upload_to='', verbose_name='Banner')),
                ('points', models.BigIntegerField(default=0, verbose_name='Estimated points')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('offer', models.FloatField(verbose_name='Offer')),
                ('is_percentage', models.BooleanField(default=True, verbose_name='Is Percentage')),
                ('rating', models.SmallIntegerField(default=0, verbose_name='Rating')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
            },
        ),
    ]
