# Generated by Django 4.1.2 on 2022-10-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_company_admin',
            field=models.BooleanField(default=False, verbose_name='Is company Admin'),
        ),
    ]
