# Generated by Django 4.1.2 on 2022-11-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_company_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribedAt',
            field=models.DateField(blank=True, null=True, verbose_name='Subscribed At'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribedExpire',
            field=models.DateField(blank=True, null=True, verbose_name='Subscribed Expire'),
        ),
    ]
